services:
  db:
    container_name: pg_server_titan
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_data_titan:/var/lib/postgresql/data

volumes:
  pg_data_titan:
